name: POC Pipeline
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build & Push to repository
    runs-on: ubuntu-latest
    env:
      IMG_NAME: yono1997/poc-table-excel
      TAGS: ${GITHUB_REF##*/}
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - name: Build and Push image
        run: |
          echo "mamangsekayu97" | docker login -u "msuryono0@gmail.com" --password-stdin
          docker image build -t ${{ env.IMG_NAME }}:${{ env.TAGS }} .
          docker push ${{ env.IMG_NAME }}:${{ env.TAGS }}